on:
  push:
    branches:
      - NOTmain # NOTE: change to main when ready
  pull_request:
    branches:
      - NOTmain # NOTE: change to main when ready
# Environment variables available to all jobs and steps in this workflow
env:
  # K8s cluster name from DigitalOcean
  KUBERNETES_CLUSTER_NAME: k8s-cluster-shared
  ANGULAR_IMAGE_NAME: recreateyourself-client
  ANGULAR_CONTAINER_NAME: recreateyourself-client
  ANGULAR_DEPLOYMENT_NAME: recreateyourself-client
jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@main

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}     #From Github secrets
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} #From Github secrets

    - name: Build and push Angular Image
      id: angular_docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./angular-client
        file: ./angular-client/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.ANGULAR_IMAGE_NAME }}:${{ github.sha }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} #From Github secrets

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 2400 ${{ env.KUBERNETES_CLUSTER_NAME }}
    # Deploy Angular Docker image to the DigitalOcean kubernetes cluster
    - name: Deploy
      run: |-
        kubectl set image deployment/${{env.ANGULAR_DEPLOYMENT_NAME}} ${{env.ANGULAR_CONTAINER_NAME}}=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.ANGULAR_IMAGE_NAME }}:${{ github.sha }}
        kubectl rollout status deployment/${{env.ANGULAR_DEPLOYMENT_NAME}}
        kubectl get services -o wide
